apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: my-app
        image: my-app:v1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "500Mi"  # Added ephemeral storage request
          limits:
            memory: "512Mi"
            ephemeral-storage: "1Gi"  # Added ephemeral storage limit
        volumeMounts:
          - name: my-storage
            mountPath: /app/data
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: my-pvc
